### ISSUE TITLE
How did you build this?

### ISSUE THREAD

**Issue by Waoweens** [safijari/sunshine-deck#2]
Hi, how did you build it? I'm trying to do this for newer sunshine versions, but I kept having dependency issues. Your binary seem to just work on a stock SteamOS image without installing anything from Pacman.

**Comment by parkerlreed** [comment]
You want the latest Flatpak from the Sunshine releases. Works out of the box and fully supports hardware encoding.

**Comment by safijari** [comment]
> You want the latest Flatpak from the Sunshine releases. Works out of the box and fully supports hardware encoding.

The flatpak used to not work in gamingmode because it couldn't get the right permissions for kms capture. Did they fix that? Guess I should try it.

> Hi, how did you build it? I'm trying to do this for newer sunshine versions, but I kept having dependency issues. Your binary seem to just work on a stock SteamOS image without installing anything from Pacman.

I just banged my head against the wall until it built locally on my deck. Honestly don't remember anymore.

**Comment by parkerlreed** [comment]
It's been working wonderfully for desktop mode which has been my use case. Not sure about within gamescope.

**Comment by safijari** [comment]
> It's been working wonderfully for desktop mode which has been my use case. Not sure about within gamescope.

Ah, yeah pretty much all builds work fine for desktop mode because it's X11 and no special permissions are needed. Gamescope is under wayland and you need elevated permissions to do full screen capture.

I should go back and implement pipewiresrc for sunshine so that it still doesn't work after the 3.5 update

**Comment by safijari** [comment]
Which update?
Are you on preview and talking about 3.5?

**Comment by geecaleb** [comment]
3.4.8 but its all good. I just decided to use steam link for my case

**Comment by SuttonX** [comment]
> Does this still work with the new steamos updates? Does sunshine need to be installed before installing this? Ive been trying to get it to work but not succeeding. I run the first .sh file and it shows nothing in the konsole after running. Tried executing sunshine run.sh but still nothing. Any help would be appreciated, thanks!

Just view the sh file and cut and paste the contents directly into Konsole.  That's what I did and it worked fine.  You'll know it worked when it returns you back to a Konsole input line

**Comment by s0th1s** [comment]
I was curious if there were any plans to update this package for the newly released 3.5.5 stable.  I noted the old install was broken and now I get a dependency error when I try to manually start the service.

I absolutely love what you guys did to get this working in game mode and desktop mode and use it daily.

Hoping a new build can be made that works again with the latest 3.5.5 stable.

**Comment by safijari** [comment]
https://github.com/safijari/sunshine-deck/blob/main/readme.md#build-instructions-for-the-cool-people-reading-this

build instructions here
