### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by callmeEthan** [safijari/sunshine-deck#4]
Followed install instruction but nothing happens. Device not shows on moonlight clients, try to access 127.0.0.1:47990 but unable to connect. Try to run run.sh in konsole return this line:
`/home/deck/sunshine-deck/usr/local/bin/sunshine: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`
Any tips?

**Comment by safijari** [comment]
What version of SteamOS?

**Comment by callmeEthan** [comment]
Version 3.5

**Comment by jerrymao15** [comment]
Seeing the same thing on 3.5 as well, was working perfect before I updated.

**Comment by alanpt** [comment]
Hi, I have the same problem. Is there a way of rolling back to before 3.5? Or is there one I can use from before? 
It feels like I'm in a very small minority trying to get nvidia card (GTX 1070) to work on Holoios (Tweaked) with Sunshine. I can get the desktop view to work on one of my Moonlight clients but not another and its not working in gamemode.

**Comment by yaseen420** [comment]
Having the same issue, on SteamOS 3.5 as well. A fix would be great! This seems to be the only possible way to using sunshine in game mode as well, or so I have heard.

**Comment by AfterCool** [comment]
When you are in 3.5, Openssl must be updated, moreover sunshine-deck needs "libicu" in version 71.
Here is the solution that corrected the problem for me:

Update openssl :
sudo pacman -S openssl-1.1

Then copy libicu and rename it:
sudo cp /usr/lib/libicudata.so.72.1 /usr/lib/libicudata.so.71.1
sudo cp /usr/lib/libicui18n.so.72 /usr/lib/libicui18n.so.71
sudo cp /usr/lib/libicuuc.so.72 /usr/lib/libicuuc.so.71
sudo cp /usr/lib/libicudata.so.72 /usr/lib/libicudata.so.71

I hope this helps.
Regards,

**Comment by yaseen420** [comment]
> When you are in 3.5, Openssl must be updated, moreover sunshine-deck needs "libicu" in version 71. Here is the solution that corrected the problem for me:
> 
> Update openssl : sudo pacman -S openssl-1.1
> 
> Then copy libicu and rename it: sudo cp /usr/lib/libicudata.so.72.1 /usr/lib/libicudata.so.71.1 sudo cp /usr/lib/libicui18n.so.72 /usr/lib/libicui18n.so.71 sudo cp /usr/lib/libicuuc.so.72 /usr/lib/libicuuc.so.71 sudo cp /usr/lib/libicudata.so.72 /usr/lib/libicudata.so.71
> 
> I hope this helps. Regards,

Can confirm, it works on SteamOS 3.5, thanks so much! I've been banging my head on this issue. 

 I also couldn't get packages to install via pacman for some reason. I disabled the steamos read-only, did sudo pacman-key --init, sudo pacman-key --populate archlinux, but no luck. It kept saying "unknown trust or package corrupted" along the lines. "error: failed to commit transaction (invalid or corrupted package (PGP signature))"

Then finally I found that you can disable checking for package signing (I'm no expert, but definitely not safe for normal use!), in /etc/pacman.conf so I did that (check 4.1.3): https://wiki.archlinux.org/title/Pacman/Package_signing

And viola, finally installed openssl-1.1, follow the instructions, and everything works like a charm, in game mode too! Appreciate it a lot!

**Comment by safijari** [comment]
Clearly I need to build again against the new versions. Sorry for not being active on this. I'll try to do this soon.

**Comment by AfterCool** [comment]
> Clearly I need to build again against the new versions. Sorry for not being active on this. I'll try to do this soon.

It's all right, it's already great that you've created sunshine-deck for us to host in game mode, thank you :)

**Comment by safijari** [comment]
Please try this build https://github.com/safijari/sunshine-deck/releases/tag/v0.21

**Comment by AfterCool** [comment]
Hi, thanks for update :+1: 
I removed the libraries to test your new version:
/usr/lib/libicudata.so.71.1
/usr/lib/libicui18n.so.71
/usr/lib/libicuuc.so.71
/usr/lib/libicudata.so.71

But I get an error when starting the service :
Regards,

![ksnip_20231118-113113](https://github.com/safijari/sunshine-deck/assets/19575239/e156dcaa-f260-49c8-b142-88b067078fe1)

**Comment by AfterCool** [comment]
> Hi, thanks for update 👍 I removed the libraries to test your new version: /usr/lib/libicudata.so.71.1 /usr/lib/libicui18n.so.71 /usr/lib/libicuuc.so.71 /usr/lib/libicudata.so.71
> 
> But I get an error when starting the service : Regards,
> 

Here's the error I get when I manually run.sh : 

![ksnip_20231118-115844](https://github.com/safijari/sunshine-deck/assets/19575239/53c058cc-72fa-4ea7-ae02-7c4f07122beb)

I only get this error on the new version of sunshine-deck.
Regards,

**Comment by safijari** [comment]
Please use new method outlined in the readme.
