### ISSUE TITLE
Failed to apply config: filesystem error: cannot copy file

### ISSUE THREAD

**Issue by CobreDev** [safijari/sunshine-deck#6]
I've installed the latest version of sunshine-deck in ~/sunshine-deck, and when I run `./run.sh`, it outputs this:

```[2023-12-14 09:58:41.118382] [0x00007fd511fd59c0] [info]    Failed to apply config: filesystem error: cannot copy file: No such file or directory [/usr/share/sunshine/apps.json] [/home/deck/.config/sunshine/apps.json]```

I'm not sure exactly what I'm supposed to do

**Comment by safijari** [comment]
use new method now listed in the readme
