### ISSUE TITLE
Sunshine Decky Plugin

### ISSUE THREAD

**Issue by s0t7x** [safijari/sunshine-deck#8]
Hi I came across the use-case of streaming game mode with sunshine. I ended up writing a simple decky plugin for toggling sunshine in game mode.

Right now the user needs to have the sunshine flatpak installed and configured as well as devices paired.

My future roadmap for this plugin includes including Send-PIN functionality and opening the webui in an embedded browser window.

[Decky Sunshine Plugin Repo](https://github.com/s0t7x/decky-sunshine)

**Comment by safijari** [comment]
That's amazing!

I suggest submitting it to the Decky store. I can help with testing.

Also you could in theory automatically download the flatpak by using a subprocesses command, or expose a button for it.

**Comment by s0t7x** [comment]
Thanks!
I want to make it a straight out-of-the-box experience. I am currently working on a way to signin to the webui and send PINs for pairing. As soon as this is working the next step will be implementing an automatic installation and support the sunshine "welcome flow".

Testing would be very handy as iam not actually used to python and i currently often crash my plugin as well as decky.
You can find the cleaned up and latest source in the "controls" branch.

Please don't hestitate to contribute to the project!

**Comment by safijari** [comment]
The plugin is on the testing store now and works perfectly.
